env:
  es2021: true
  node: true
  jest/globals: true
parser: '@typescript-eslint/parser'
extends:
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 13
  sourceType: 'module'
plugins:
  - '@typescript-eslint'
  - 'jest'
rules: {
  'no-new': 0,
  'import/prefer-default-export': 0,
}
