module Slack
  class Client
    @webhook_url: String
    @client: Faraday::Connection

    attr_reader webhook_url: String

    def post: (content: String) -> Faraday::Response

    private

    def initialize: (webhook_url: String?) -> void

    def client: -> Faraday::Connection
  end
end
