class Yuru28FeedParser
  @client: Faraday::Connection
  @feed: Nokogiri::XML::Document

  def self.parse: -> Array[Hash[Symbol, String | Date]]

  def parse: -> Array[Hash[Symbol, String | Date]]

  private

  def client: -> Faraday::Connection

  def base_url: -> String

  def feed_path: -> String
end
