D = Steep::Diagnostic

target :lib do
  signature "sig"

  check "lib"
  check "models"

  repo_path "vendor/rbs/gem_rbs/gems"

  library "uri"
  library "forwardable"

  library "faraday"
  library "nokogiri"

  configure_code_diagnostics do |hash|
    hash[D::Ruby::MethodDefinitionMissing] = :warning
    hash[D::Ruby::UnknownConstant] = :information
  end
end
